### ISSUE TITLE
Implement MotorSafetyHelper

### ISSUE THREAD

**Issue by CarlyAmar** [Chantilly612Code/612-2015#102]
Make a print statement and allow us to check up on the motors by using drivetrain->m_safetyHelper and calling the appropriate functions. Make sure to enable the safety in the drivetrain constructor and to set expiration (it is a float measured in seconds) and make it a variable declared in RobotMap.h

So:
Check and print if it is alive
Set the safety
Set the expiration

**Comment by CarlyAmar** [comment]
We need to do the IsAlive() function to check and print in the case of a timeout. Do this in a later commit

**Comment by WardBenjamin** [comment]
Complete as per http://www.chantillyrobotics.org/forum/index.php/topic,906.0.html and https://github.com/Chantilly612Code/612-2015/commit/1be074ae9fd43d7945c5399dafd5dab22e881bf4
