### ISSUE TITLE
Debug the MotorSafetyHelper Timeout

### ISSUE THREAD

**Issue by CarlyAmar** [Chantilly612Code/612-2015#108]
There is an issue where the code crashes because of a timeout in motor safety. We need to keep the safety on because if we don't have it on, it can lose control.

**Comment by WardBenjamin** [comment]
If you assign yourself or someone else, don't forget to remove the `help-wanted` label.

**Comment by nls5260** [comment]
I dont know i this may help but I found this forum post on the FIRST website forum on this issue

http://forums.usfirst.org/showthread.php?24030-C-Need-Help!

**Comment by WardBenjamin** [comment]
Complete as per http://www.chantillyrobotics.org/forum/index.php/topic,906.0.html and https://github.com/Chantilly612Code/612-2015/commit/1be074ae9fd43d7945c5399dafd5dab22e881bf4.
