### ISSUE TITLE
Use IR sensors on end of fork to determine crate alignment.

### ISSUE THREAD

**Issue by CharlesCDietzel** [Chantilly612Code/612-2015#128]
So what Zack said is that the forks of the robot have IR sensors on the bottom, which are facing directly down. If these sensors are able to see the ground, the tote is properly aligned with the forks. If only one is able to see the ground, and the other is seeing the tote, is is misaligned. Make a method to determine if the elevator is aligned.

**Comment by calvin-godfrey** [comment]
Done!
