### ISSUE TITLE
Autonomous-Auto-Align

### ISSUE THREAD

**Issue by Alexbay218** [Chantilly612Code/612-2015#145]

**Comment by Alexbay218** [comment]
![autoaligntrigonometry](https://cloud.githubusercontent.com/assets/9091117/6139684/71d1aae6-b15c-11e4-8137-37568e8ccaa4.png)
![autoalignvisualization complex](https://cloud.githubusercontent.com/assets/9091117/6139685/71d2fb3a-b15c-11e4-87a3-33c426dcb554.png)
![autoalignvisualization](https://cloud.githubusercontent.com/assets/9091117/6139686/71d5920a-b15c-11e4-83d2-a6215b0d9a19.png)
![measuringtoteangle](https://cloud.githubusercontent.com/assets/9091117/6139687/71d60456-b15c-11e4-8071-8621ecb71c09.png)

**Comment by Alexbay218** [comment]
unneeded

**Comment by ghost** [comment]
Unneeded for now but might implement later if we have time or as  an off season project
