### ISSUE TITLE
Detecting breaker flip

### ISSUE THREAD

**Issue by Alexbay218** [Chantilly612Code/612-2015#150]
There is a motor that will flip the breaker when it draws to much power.

We need to detect if the breaker is flipped by measuring the current the PDB draws, by detecting when a sudden current drop occurs.

Occurs in the elevator motor.

Use a encoder value and a timer to test if the component is moving. If not, the tell PID to stop moving.

May be a mechanical issue.

**Comment by ghost** [comment]
This should be one of the last pieces of code we right because if mechanical does their job this shouldn't even happen.

**Comment by CarlyAmar** [comment]
I want to have something like this implemented whenever we aren't working on anything else. This could be a general feature that can be implemented in multiple motors as a general safety to be reused yearly.

**Comment by ghost** [comment]
Agreed, I just want everyone to keep priorities for last few days of build season.

**Comment by CharlesCDietzel** [comment]
This was fixed in hardware. Closing.
