### ISSUE TITLE
Elevator Lift Tolerance

### ISSUE THREAD

**Issue by ghost** [Chantilly612Code/612-2015#165]
We need a tolerance for isFinished for the elevator loft command because otherwise it will never end. Please fix this Not Zack

**Comment by CharlesCDietzel** [comment]
Yo, Fixed this in bugfix-warehouse branch, which should be pushed into master sometime soon.

**Comment by CharlesCDietzel** [comment]
Bugfix warehouse was pushed so long ago its nuts. I don't even remember when i fixed this. Anyway, I'm gonna close this issue.
