### ISSUE TITLE
Calibrate and Test Encoders and Nav Board

### ISSUE THREAD

**Issue by CarlyAmar** [Chantilly612Code/612-2015#179]
Needed for #178 navigation

**Comment by calvin-godfrey** [comment]
[Here is a link](https://code.google.com/p/navxmxp/source/browse/#svn%2Ftrunk%2Froborio%2Fc%2B%2B%2FnavXMXP_CPlusPlus_RobotExample%2Fsrc) to code that we can use. Not sure how to implement this.

**Comment by CharlesCDietzel** [comment]
Get on this guys. You have actually been working on this one task for like a month now. you should be done.

**Comment by PaolaHenriquez** [comment]
Testing calibration is done!! Now for the code!

**Comment by CharlesCDietzel** [comment]
This is sufficiently done that I don't care anymore. Closing.
