### ISSUE TITLE
Have the Arduino effectively transfer camera information to the RoboRio over I2C

### ISSUE THREAD

**Issue by ZachPerkins1** [Chantilly612Code/612-2015#192]
This should have been an issue a long time ago. I'm making it now so I have something to tag in my commits.

**Comment by WardBenjamin** [comment]
This issue is already marked, actually. See https://github.com/Chantilly612Code/612-2015/issues/154 for more details.

**Comment by ZachPerkins1** [comment]
Thanks, didn't see that!
