### ISSUE TITLE
Choose names for the software projects of the robot

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2015#21]
I'd like a name for the:
- C++ project
- Vision processing project

**Comment by WardBenjamin** [comment]
May I suggest Ascendor?

**Comment by CarlyAmar** [comment]
I suggest Clank, because last year the robot official name was Ratchet

**Comment by WardBenjamin** [comment]
Not bad.

**Comment by Alexbay218** [comment]
I like Clank

(i get the reference :)

**Comment by CharlesCDietzel** [comment]
I actually like clank too. Purely because of the name, not the reference.

**Comment by toastertaster** [comment]
We didn't ask today, but perhaps last call is on Tuesday.  I'd like this to be decided by then, and this issue closed by Tuesday night.

**Comment by WardBenjamin** [comment]
Definitely. That works for me, and I'm sure that will be fine with everyone else.

**Comment by CharlesCDietzel** [comment]
I uhh... don't know if this issue can ever really be closed until the name is actually finalized, which may or may not ever actually ever happen. So I kind of feel like this issue should either be closed now and moved to the forums where it can live on indefinitely, or else be closed... or something... I don't actually know. Thoughts?

**Comment by CarlyAmar** [comment]
CLANK!!!!!!!
