### ISSUE TITLE
Correctly set up Driver Station laptop

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2015#22]
I want someone to set up one of the E12 laptops and one of the ASUS Laptops to be a driver station.

From Ron Baer (read _thoroughly_)
We have 2 classmate E12 laptops as driver stations.  I upgraded 1 to 2015 by re-imaging it.  It has a post-it note saying 2015 driver station.  I imaged the laptop and ran the Windows upgrades.  It still need the Jan 2015 FRC updates applied.  It also has the development station configuration. FYI, __before re-imaging the 2nd classmate, I would verify that the 2015 driver station can control last year's robot.  Otherwise, I would keep the 2nd classmate at 2014 driver station.__  Their is a orange, bootable thumbdrive in the rear pocket of the driver station laptop case, with a tag saying 2015 E12 Image.  Just insert it an reboot to the thumbdrive.  Instructions are also on linked to the FIRST website.  Note that there may be some files to be copied off the 2nd laptop before re-imaging.  I did copy a block of files of the 1st classmate.

**Comment by WardBenjamin** [comment]
Jeff Tolbert said he'd take care of this in addition to adding the driver station to his own laptop.

**Comment by toastertaster** [comment]
Good insight.  You should assign this issue to Jeff in the right side column.

**Comment by WardBenjamin** [comment]
Done. I need to remember that I can add people other than myself to tasks.

**Comment by WardBenjamin** [comment]
I'm handeling the E12, but @JeffTolbert still needs to install the driver station on his own laptop.

**Comment by WardBenjamin** [comment]
Alright, 2015 Update downloaded and is unzipping (taking about 20 years though). The NI thing for the vision software will take another 19 mins to download, so idk if this will be done tonight since I have to install that first.
