### ISSUE TITLE
Creating the most simple autonomous

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2015#25]
After #24 is closed, create the code in the appropriate file for 
- a simple Autonomous to drive forward for 4 seconds and stop.  Implemented as a Command     AutonomousSimple

**Comment by Alexbay218** [comment]
should be simple. I'll try this one

**Comment by toastertaster** [comment]
Need work against commit SHA: a5227fe8d9b507d09ebc0b923c037ce489ddc03b
1. CommandAutonomousSimple::Execute() has errors  Cannot use Talon(N) in this manner.  (You should call a subsystem method to do this instead of trying to have 4 variables)
2. CommandAutonomousSimple::End() has errors Cannot delete Timer (which is a class, not a variable)
3. Please don't do a -> b() but do use a->b()  (bad spacing)

**Comment by Alexbay218** [comment]
Zack should have fix the errors
