### ISSUE TITLE
All members must enable notifications on the programming forum

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2015#26]
After logging into the Chantilly forums, Click Programming, On the right side click Notify (above the list of threads).  

Also do this for the Announcements topic.

Leave a comment below that you have done this.

**Comment by calvin-godfrey** [comment]
Calvin Godfrey, done.

**Comment by WardBenjamin** [comment]
Benjamin Ward, done. Also, everyone needs to be "watching" this repository to see updates in issues, etc. Tell people to do this if they haven't already.

**Comment by CarlyAmar** [comment]
I'm not going to have notifications since I always check all forums anyway.

**Comment by WardBenjamin** [comment]
Just do it @ZackAlfakir. I check the forums all of the time as well, but
getting notifications via email gets the messages to me much quicker.

On Sun, Jan 11, 2015 at 9:45 PM, ZackAlfakir notifications@github.com
wrote:

> I'm not going to have notifications since I always check all forums anyway.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Chantilly612Code/612-2015/issues/26#issuecomment-69525053
> .

## 

Benjamin Ward

**Comment by CharlesCDietzel** [comment]
Champ Dietzel, Done.

**Comment by Ahmad-Bamba** [comment]
Ahmad Bamba. Done.

**Comment by ZachPerkins1** [comment]
A bit late but, Zach Perkins, Done.

**Comment by CarlyAmar** [comment]
Everyone said they did ! :smiley:
