### ISSUE TITLE
Correctly set up D-link router

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2015#29]
Use the D-link router configuration tool to set up the D-link.

**Comment by WardBenjamin** [comment]
I think that this should be done next meeting if possible. It would make it possible for others than Zack and I to deploy code more easily.

**Comment by CarlyAmar** [comment]
I dont believe we actually have power for the router yet, so we need to talk to electrical. Also, configuring the router is done by the FRC bridge configuration tool FYI

**Comment by WardBenjamin** [comment]
If you remember, we got it on the second day that we got the kitbot. I don't know where it is currently, but it was attached to the kitbot when we last had it. Hopefully mechanical hasn't lost it.

**Comment by toastertaster** [comment]
I saw @ChampD do this today. Hooray!
