### ISSUE TITLE
Set up the camera for the robot

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2015#34]
It probably needs to be configured correctly according to the WPI screensteps live website.

See about getting it working with the robotrio after it is configured.

**Comment by WardBenjamin** [comment]
@swarage has there been progress on this since you have begun? The deadline for the Week 2 Robot milestone is past due by 8 days, and I am fairly sure that this is currently the last unfinished issue that was slated to be finished then.

**Comment by swarajd** [comment]
Yeah I'll probably get around to this step on Tuesday. The process is super simple and takes 5 minutes, so it shouldn't be that hard to do.

**Comment by toastertaster** [comment]
I'd like this done by COB Saturday, but feel free to get it done before the weekend.

**Comment by swarajd** [comment]
The camera has been set up, and we can get a feed from smart dashboard, but one thing is that I haven't found is how to connect the camera feed from the usb camera to roborealm. I HAVE found out how to connect the axis camera, however.
