### ISSUE TITLE
Install Roborealm on your computer

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2015#35]
Who is interested in working on vision ?

I have the new RoboRealm licenses, but only a few computers can have it installed.  So need to determine who is going to do this.

**Comment by Ahmad-Bamba** [comment]
Vision is something that I really wanted to work on. Once we have more info on how vision will work that is.

**Comment by WardBenjamin** [comment]
Have at it, @Ahmad-Bamba.

**Comment by WardBenjamin** [comment]
I believe that at this point the relevant people have acquired licenses for all needed software. If I am incorrect, this issue can be reopened.
