### ISSUE TITLE
Mecanum drive programming options

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2015#36]
After our visit to Oakton, we might hear about what they have done.  We can look online for existing implementations, or work on our own if necessary.

Who wants to work on this?

**Comment by Ahmad-Bamba** [comment]
I can take a look at it. Do you have any notes from Oakton we can look at?

**Comment by toastertaster** [comment]
We learned:
- Oakton used 1 joystick.  Left/Right were strafing.  The joystick z-axis (twisting) is rotation.  Swaraj indicated that you all want to use an x-box controller, so you'd have buttons to do rotation (or strafing) instead.
- WPI Lib has a Mecanum class to use (not in RobotDrive, but its own class)
- Combining strafing directions, the robot can do things like rotation+strafing, strafing in two directions at the same time (i.e., forward-right strafing by combining the two).  You can think of this like vector addition.
- The wheels were oriented in an X pattern (say, >><<) (from looking above the robot, looking down into it).  This could be done the opposite manner too (say, <<>> or diamond formation for lack of a better way to describe it).
- They used 8" mecanum wheels.
- The robot had a tendency to sit on 3 of the 4 wheels, so performance is better on carpet instead of hard tile floors.

**Comment by toastertaster** [comment]
Please assign yourself to this issue if you want to work on it.

**Comment by saileshsridhar** [comment]
I will help Ahmad.

**Comment by CharlesCDietzel** [comment]
I am also helping.

**Comment by CharlesCDietzel** [comment]
As far as i can tell, this was finished in #58. Closing.
