### ISSUE TITLE
Add sponsors to README.md 

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2015#39]
the branch `doc-README` has some improvements to the README.md file.  I think it would be prudent to add the team's sponsors to the README.  Do so above the list of contributors.

**Comment by CharlesCDietzel** [comment]
Do we have a list of sponsors? If so, where are they?

**Comment by toastertaster** [comment]
We need to make sure @PaolaHenriquez has a list of sponsors to post.  It doesn't have to be complete, but I want something added to the `README.md` by this weekend.  We'll adjust the list if sponsors change.

**Comment by nls5260** [comment]
I submitted a pull request #122 that resolves this issue
