### ISSUE TITLE
PDB Class

### ISSUE THREAD

**Issue by CarlyAmar** [Chantilly612Code/612-2015#51]
Create a class that will monitor the power draw of the PDB and the analog breaker for power

**Comment by toastertaster** [comment]
Wow, this is a great idea!  I want this in week 3, so I'm assigning the milestone.

**Comment by toastertaster** [comment]
@ggodfrey Did you think you got this done?  I think so.  Close if so.

**Comment by calvin-godfrey** [comment]
I think I got it done. There's not any errors on it (that I know of) when Zack compiled it on his laptop.
