### ISSUE TITLE
Add a url to the project README.md for documentation

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2015#59]
Since Zach has posted updated documentation to the `gh-pages` branch, we should put a link to the web address for it https://chantilly612code.github.io/612-2015/ in the `README.md` file.  

Rather than just pasting the URL in the file, add a section on Documentation and include a description of what this documentation is related to.  You'll have to use [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax to do this correctly.  GitHub also has some [Markdown guidance](https://guides.github.com/features/mastering-markdown/).

**Comment by CharlesCDietzel** [comment]
Finished with #76. Closing.
