### ISSUE TITLE
Test Mecanum Drive

### ISSUE THREAD

**Issue by calvin-godfrey** [Chantilly612Code/612-2015#65]

**Comment by CarlyAmar** [comment]
So Ahmad's branch didnt work. I was working on it earlier, I'll try to get some done before the meeting, Ahmads Command Branch would time out the motor safety and then I made an iterative robot implementation that would not properly drive (but it did drive!)

**Comment by toastertaster** [comment]
Okay! This warrants digging into the wpilib code to investigate. Thanks

**Comment by CarlyAmar** [comment]
This has been completed with the Kitbot using TalonSR, but I want to try it with CANTalonSRX and using Commands. I did my test Iterative-Style. The Iterative-Style version is now in the kitbot branch, but we should make it into a command. READ THE COMMENTS!!! some important stuff we discovered is in there

**Comment by toastertaster** [comment]
Are you doing this during the week or is this something happening this weekend?

**Comment by CarlyAmar** [comment]
Right now we are doing it with the Talon SRX. Almost got it working

**Comment by WardBenjamin** [comment]
It seems to be working fine, excepting a few wheels that fell off courtesy of mechanical. The wheels have a fairly large degree of slippage, which we will probably have to compensate for with sensors during autonomous.

**Comment by CarlyAmar** [comment]
Except when it crashes almost every time

**Comment by calvin-godfrey** [comment]
Page 34-35 [here](http://users.wpi.edu/~bamiller/WPILib/WPILib.pdf) has some sample code to drive in a straight line even if it gets bumped left/right.

**Comment by CharlesCDietzel** [comment]
Has any progress on this been made?

**Comment by calvin-godfrey** [comment]
No progress on accounting for slippage that I know of.

**Comment by CharlesCDietzel** [comment]
Its good enough that it is no longer a priority. When we implement encoder based movement, this should pretty much end up as a part of that. Closing this.
