### ISSUE TITLE
Investigate using LEDs on the robot as feedback to the driver

### ISSUE THREAD

**Issue by ZachPerkins1** [Chantilly612Code/612-2015#67]

**Comment by WardBenjamin** [comment]
This is definitely a viable communication method, however what use could be had from this? If no large gain could be made from this, it may be a good idea to move on from this and focus on other tasks.

**Comment by toastertaster** [comment]
Did you find any other hardware LEDs to consider?  We'd have to order them soon in order to put them on the robot in time.

They are very cheap, so let's just plan on getting some.

**Comment by nls5260** [comment]
After talking to Dr. Axtell we decided to use Flora Neopixel Rings.

**Comment by nls5260** [comment]
Even though Jeff posted this in the forum, this is the board that we need to purchase in order to use the flora neopixel ring lights.
http://www.andymark.com/product-p/am-2996.htm&Click=35018
