### ISSUE TITLE
Create 2 programmed Elevator positions to carry totes (changed via button push)

### ISSUE THREAD

**Issue by ZachPerkins1** [Chantilly612Code/612-2015#68]

**Comment by toastertaster** [comment]
@ZachPerkins1 are you working on this?  Why is it assigned to @Ahmad-Bamba if so.  Please assign it to yourself if you're already doing this.  Also push your commits so far so we can check it out.

**Comment by toastertaster** [comment]
Please push commits, I still don't see any on this and I'd like to review the code.

**Comment by calvin-godfrey** [comment]
Looks like it's done
