### ISSUE TITLE
Latch Open and Close

### ISSUE THREAD

**Issue by PaolaHenriquez** [Chantilly612Code/612-2015#74]
I'll start working on this when Calvin moves Latch to the correct file

**Comment by CarlyAmar** [comment]
This is now in `master` so you can pick one of these to do and then assign it to yourself!  The other one should be a separate issue so that someone else can work on it

**Comment by toastertaster** [comment]
I added comments to your branch `feature-latch`, so keep going on development @PaolaHenriquez

**Comment by PaolaHenriquez** [comment]
Finished Latch!!
