### ISSUE TITLE
Robot.cpp does not compile in master. Feeeexxxx eeettttt.

### ISSUE THREAD

**Issue by CharlesCDietzel** [Chantilly612Code/612-2015#75]

**Comment by CharlesCDietzel** [comment]
Closing this.

**Comment by CarlyAmar** [comment]
Champ, you closed/locked topic, but it has not been resolved. Are you actively working on this?

**Comment by CharlesCDietzel** [comment]
Its.. a long story. Anyway, the reason i closed it is not actually valid anymore. So I'll reopen it.

**Comment by CarlyAmar** [comment]
Ill fix it
