### ISSUE TITLE
Deploy the master branch to the RobotRIO demo board ...

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2015#90]
And verify that we don't have any runtime errors yet for the robot code.

This needs to happen after Champ does #88 .

**Comment by WardBenjamin** [comment]
I will take care of this as soon as possible. At the moment, my copy of the code compiles fine, but I cannot verify that there is no runtime errors until we actually run it on the robot, as was said.

**Comment by WardBenjamin** [comment]
The code seems to deploy and run correctly on both the kitbot and the practice board, excepting a few runtime errors on the practice board because it lacks the full suite of motor controllers.

**Comment by WardBenjamin** [comment]
Reopening because the code fails because of MotorSafety timeouts after a few minutes, inconsistantly.

**Comment by toastertaster** [comment]
Done!!!!!!!!
