### ISSUE TITLE
Command to move the robot based on camera information

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2015#92]
If we have a camera with a view of the tote, we'd ideally like to center the robot to the tote.  We could really use a `Command` that commanded the motors to move based on reading some variables from the NetworkTable.

For the first attempt, assume we get an `x` and `y` pixel coordinate and that we wish to move the robot such that `x` tends to a value `xDesired` and `y` tends to `yDesired`

Show me what you got!

**Comment by WardBenjamin** [comment]
I don't know when this will be completed, but I'm assigning this to swaraj because he is the one who knows the most about the camera, etc.

**Comment by WardBenjamin** [comment]
I am going to add a template for this so that I can complete the command group, but will leave it empty so that swaraj can fill it in.

**Comment by ghost** [comment]
Changed to help wanted because swaraj doesn't come to enough meetings. Also this is not high priority before bag and tag.

**Comment by CharlesCDietzel** [comment]
Swaraj, Follow rule 1! All day Erey' Day!

**Comment by CharlesCDietzel** [comment]
This sounds pretty much identical to what I am going for with #126. So I am going to just assign this to myself to do alongside that.

**Comment by CharlesCDietzel** [comment]
Eh, closing due to redundancy. Srsly folks, stop making so many issues that are the same.
