### ISSUE TITLE
CommandGroup to approach the tote, latch the tote

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2015#93]
WPILib has a `CommandGroup` class that performs a series of individual `Command`s.  What we desire here is to show that we can drive forward (perhaps until the camera sees the tote centered as in #92 ) and then latch onto the tote.

See https://chantilly612code.github.io/612-2015/class_command_group.html for documentation

**Comment by CharlesCDietzel** [comment]
93.6% sure this will be done with auto align. Therefore closing this due to redundancy.
