### ISSUE TITLE
Our second autonomous mode

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2015#94]
We only have one autonomous mode, so let's get another one made.

I leave it to your discretion as what the robot performs, but it should be more than the first autonomous mode.

**Comment by Ahmad-Bamba** [comment]
About autonomous, this really should be a command group. So while we don't have vision working quite yet, it doesn't mean we can't brainstorm what tiny commands our second autonomous can have.

**Comment by CharlesCDietzel** [comment]
Well, this was sort of done at competition, when Zack wrote a sideways autonomous in the constructor of autonomous Simple. You just have to pass true as the third value in the constructor and it goes sideways. So ima close dis.
